modLoader="javafml" #mandatory

loaderVersion="[32,)" #mandatory

authors="Shadows_of_Fire" #optional

license="MIT License" #mandatory

[[mods]] #mandatory

modId="placebo" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Placebo" #mandatory

description='''
1 (one) library boi
'''

[[dependencies.placebo]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35.1.36,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.placebo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,)"
    ordering="NONE"
    side="BOTH"