modLoader="javafml" #mandatory

loaderVersion="[27,)" #mandatory

authors="Shadows_of_Fire" #optional

[[mods]] #mandatory

modId="placebo" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Placebo" #mandatory

description='''
1 (one) library boi
'''

[[dependencies.apotheosis]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[27,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.apotheosis]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"